### ISSUE TITLE
CMake configuration fails

### ISSUE THREAD

**Issue by niansa** [0xc0de/AngieEngine#1]
CMake Error at Engine/CMakeLists.txt:5 (setup_msvc_runtime_library):
      Unknown CMake command "setup_msvc_runtime_library".
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/pi/Projects/AngieEngine/Source/Build/CMakeFiles/CMakeOutput.log".

**Comment by 0xc0de** [comment]
> ```
> CMake Error at Engine/CMakeLists.txt:5 (setup_msvc_runtime_library):
>   Unknown CMake command "setup_msvc_runtime_library".
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/pi/Projects/AngieEngine/Source/Build/CMakeFiles/CMakeOutput.log".
> ```

Please look at this sample: https://github.com/0xc0de/EmptyProject
You should take from there the cmakelists.txt for your project.

**Comment by niansa** [comment]
Thanks a huge lot!
